Update deploy-app.yml

diff --git a/.github/workflows/deploy-app.yml b/.github/workflows/deploy-app.yml
--- a/.github/workflows/deploy-app.yml
+++ b/.github/workflows/deploy-app.yml
@@ -79,15 +79,22 @@ jobs:
         MONGO_PASS=$(gcloud secrets versions access latest --secret='mongodb-password' | tr -d '\n')
         JWT_KEY=$(gcloud secrets versions access latest --secret='jwt-secret-key' | tr -d '\n')
         echo "::endgroup::"
-        
-        echo "::group::Retrieving MongoDB VM IP Address"
+
+        MONGO_HOSTNAME= "mongodb-vm"
+        # echo "::group::Retrieving MongoDB VM IP Address"
         # MongoDB VMの内部IPアドレスを取得
-        MONGO_IP=$(gcloud compute instances describe mongodb-vm --zone asia-northeast1-a --format='get(networkInterfaces[0].networkIP)')
-        echo "MongoDB VM Internal IP: $MONGO_IP"
-        echo "::endgroup::"
+        # MONGO_IP=$(gcloud compute instances describe mongodb-vm --zone asia-northeast1-a --format='get(networkInterfaces[0].networkIP)')
+        # echo "MongoDB VM Internal IP: $MONGO_IP"
+        # echo "::endgroup::"
 
         # Validate variables
-        if [[ -z "$MONGO_USER" || -z "$MONGO_PASS" || -z "$MONGO_IP" ]]; then
+        # if [[ -z "$MONGO_USER" || -z "$MONGO_PASS" || -z "$MONGO_IP" ]]; then
+        # echo "::error::One or more MongoDB connection variables are empty!"
+        # exit 1
+        # fi
+
+        # Validate variables
+        if [[ -z "$MONGO_USER" || -z "$MONGO_PASS" || -z "$MONGO_HOSTNAME" ]]; then
         echo "::error::One or more MongoDB connection variables are empty!"
         exit 1
         fi
@@ -95,6 +102,10 @@ jobs:
         # 接続文字列を構築
         # MONGO_URI="mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_IP}:27017/todo_db?authSource=admin"
         # echo "Constructed MONGODB_URI (password hidden): mongodb://${MONGO_USER}:***@${MONGO_IP}:27017/todo_db?authSource=admin"
+
+        # 接続文字列を構築
+        MONGO_URI="mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOSTNAME}:27017/todo_db?authSource=admin"
+        echo "Constructed MONGODB_URI (password hidden): mongodb://${MONGO_USER}:***@${MONGO_HOSTNAME}:27017/todo_db?authSource=admin"
 
         # Kubernetes Secretを作成（存在すれば更新）
         kubectl create secret generic wiz-app-secrets \
